# Generated by Django 4.2.3 on 2023-09-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SaffronCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Saffron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy', models.BooleanField()),
                ('gram_price', models.IntegerField()),
                ('weight_gram', models.FloatField()),
                ('all_amount_tmn', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('payments', models.ManyToManyField(to='saffron.payment')),
                ('saffron_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saffron.saffroncategory')),
            ],
        ),
    ]
