# Generated by Django 4.2.3 on 2023-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saffron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saffron',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
